### ISSUE TITLE
Stuck at "Python is either not working, is missing required modules ..."

### ISSUE THREAD

**Issue by llelectronics** [ds9-extras/0-toggle#3]
Installed the plasmoid on Netrunner Core. It installed the required python modules though anyway I get this dialog. Clicking the link in it to install the packages does show a progress loading circle and goes back to the same error message as before. 

pydoc modules is running and using 100% cpu all the time. (seems to respawning all the time as it is getting a new pid  almost every second)

**Comment by llelectronics** [comment]
pydocs timeout it to short (4 second). It should be raised to 30 seconds.

**Comment by leinir** [comment]
Timeout raised in 4e8aa2b96235051944c60bbc9fb8c21bb47f18da
